FROM node:21.7.3-alpine

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /app

COPY package*.json ./

# Installing dependencies
RUN npm install

# Copying all the files in our project
COPY . .

# Starting our application
CMD [ "node", "--test" ]

# Exposing server port
EXPOSE 4444
