# Fetching the minified node image on apline linux
FROM node:21.7.3-alpine

# Declaring env
ENV NODE_ENV production

# Setting up the work directory
WORKDIR /app

COPY package*.json ./

# Installing dependencies
RUN npm install

# Installing pm2 globally
RUN npm install pm2 -g

COPY . .

# Starting our application
CMD pm2 start index.js && tail -f /dev/null

# Exposing server port
EXPOSE 4444